[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ezdxf>=1.4.1",
    "matplotlib>=3.10.1",
    "pillow>=11.2.1",
]
