meta:
  engine: 4.1.0
  name: xs18
  version: 0.1
  author: Roming22
  url: https://github.com/Roming22/xs18
presets:
  choc_v1:
    sw_x: 14      # Key plate footprint horizontal
    sw_y: 14      # Key plate footprint vertical
    capx: 17.5    # Keycap size horizontal
    capy: 16.5    # Keycap size vertical
units:
  # Keyboard geometry
  side_angle: 22    # Angle between the index column and the X axis
  ring_offsety: 7     # Vertical offset between pinky and ring columns
  middle_offsety: 4   # Vertical offset between ring and middle columns
  index_offsety: -6   # Vertical offset between middle and index columns
  thumb_offsetx: 12   # Horizontal distance between the index column and home thumb key
  thumb_offsety: 3    # Vertical distance between the index column and home thumb key
  # Defaults/Constants
  $default_height: 0  # Points invisible by default unless height/width explicitly set
  $default_width: 0
  $extends: presets.choc_v1
  kx: capx + 1    # Key spacing horizontal
  ky: capy + 1    # Key spacing vertical
points:
  zones:
    matrix:
      key:
        width: capx
        height: capy
        spread: kx
        padding: ky
      rows:
        home: {}
        top: {}
      columns:
        pinky:
          rows:
            top:
              skip: true
        ring:
          key:
            stagger: ring_offsety
        middle:
          key:
            stagger: middle_offsety
        index:
          key:
            stagger: index_offsety
      mirror:
        ref: matrix_index_top
        distance: 5kx
      rotate: -side_angle
    thumb:
      anchor:
        ref: matrix_index_home
        shift: [thumb_offsetx, -ky-thumb_offsety]
      key.$extends: points.zones.matrix.key
      columns:
        home: {}
        outer: {}
      mirror.$extends: points.zones.matrix.mirror
outlines:
    __key_outline:
      - what: rectangle
        bound: false
        size: [kx+1, ky+1]
        where:
          - /matrix_.*/
          - /thumb_.*/
    _board:
      - name: __key_outline
        fillet: 1.5
    _keycaps:
      - what: rectangle
        size: [capx, capy]
        where:
          - /matrix_.*/
          - /thumb_.*/
    _switches:
      - what: rectangle
        size: [sw_x, sw_y]
        where:
          - /matrix_.*/
          - /thumb_.*/
    keyboard:
      - _board
      - ^_keycaps
    switchplate:
      - _board
      - operation: subtract
        name: _switches
        fillet: 0.5