meta:
  engine: 4.1.0
  name: xs18
  version: 0.1
  author: Roming22
  url: https://github.com/Roming22/xs18
presets:
  choc_v1:
    sw_x: 14      # Key plate footprint horizontal
    sw_y: 14      # Key plate footprint vertical
    capx: 17.5    # Keycap size horizontal
    capy: 16.5    # Keycap size vertical
units:
  # Keyboard geometry
  side_angle: 40        # Angle between the index column and the X axis
  mirror_distance: 35   # Distance between the top of the index column and the X axis
  ring_angle: 7     # Angle between pinky and ring columns
  middle_angle: 2   # Angle between ring and middle columns
  index_angle: 11   # Angle between middle and index columns
  ring_offsetx: 1     # Horizontal offset between pinky and ring columns
  middle_offsetx: 0   # Horizontal offset between ring and middle columns
  index_offsetx: 1    # Horizontal offset between middle and index columns
  ring_offsety: 4     # Vertical offset between pinky and ring columns
  middle_offsety: 4   # Vertical offset between ring and middle columns
  index_offsety: -6   # Vertical offset between middle and index columns
  thumb_angle: 7   # Angle between index columns and the home thumb key
  thumb_splay: 11   # Angle between the thumb columns
  thumb_offsetx: 11   # Horizontal distance between the index column and home thumb key
  thumb_offsety: 3    # Vertical distance between the index column and home thumb key
  thumb_spread: 1   # Horizontal distance between the thumb columns
  thumb_tuney: -2    # Tune the vertical distance between the thumb columns
  # Defaults/Constants
  $default_height: 0  # Points invisible by default unless height/width explicitly set
  $default_width: 0
  $extends: presets.choc_v1
  kx: capx + 1    # Key spacing horizontal
  ky: capy + 1    # Key spacing vertical
  xiao_x: 17.8
  xiao_y: 21
  mcu_x: xiao_x
  mcu_y: xiao_y
points:
  zones:
    matrix:
      anchor.shift: [200, -50]  # Fix placement on KiCAD sheet
      key:
        width: capx
        height: capy
        spread: kx
        padding: ky
      rows:
        home:
          row_net: P6
          mirror:
            row_net: P4
        top:
          row_net: P29
          mirror:
            row_net: P5
      columns:
        pinky:
          key:
            column_net: P0
            mirror:
              column_net: P1
            splay: ring_angle+middle_angle+index_angle
          rows:
            top:
              skip: true
        ring:
          key:
            column_net: P7
            mirror:
              column_net: P2
            splay: -ring_angle
            spread: kx+ring_offsetx
            stagger: ring_offsety
        middle:
          key:
            column_net: P2
            mirror:
              column_net: P7
            splay: -middle_angle
            spread: kx+middle_offsetx
            stagger: middle_offsety
        index:
          key:
            column_net: P1
            mirror:
              column_net: P0
            splay: -index_angle
            spread: kx+index_offsetx
            stagger: index_offsety
      mirror:
        ref: matrix_index_top
        distance: 2mirror_distance
      rotate: -side_angle
    thumb:
      anchor:
        ref: matrix_index_home
        shift: [thumb_offsetx, -ky-thumb_offsety]
      key.$extends: points.zones.matrix.key
      columns:
        home:
          key:
            column_net: P0
            mirror:
              column_net: P1
            splay: -thumb_angle
        outer:
          key:
            column_net: P7
            mirror:
              column_net: P2
            splay: -thumb_splay
            spread: kx+thumb_spread
            stagger: thumb_tuney
      mirror.$extends: points.zones.matrix.mirror
    reference_top_center:
      anchor:
        aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
    mcu:
      anchor:
        ref: reference_top_center
        shift: [0, -0.5xiao_y]
      key:
        width: xiao_x
        height: xiao_y
outlines:
    __key_outline:
      - what: polygon
        points:
          - ref: thumb_outer
            shift: [0.5kx+1, 0.5ky+10]
          - ref: thumb_outer
            shift: [0.5kx+1, -0.5ky-1]
          - ref: matrix_index_home
            shift: [0, -0.5ky-20]
          - ref: matrix_pinky_home
            shift: [-0.5kx-1, -0.5ky-1]
          - ref: matrix_pinky_home
            shift: [-0.5kx-1, 0.5ky]
          - ref: matrix_middle_top
            shift: [-1.5kx-2.5, 0.5ky+1]
          - ref: matrix_middle_top
            shift: [1.5kx-2, 0.5ky+1]
          - ref: mirror_matrix_middle_top
            shift: [1.5kx-2, 0.5ky+1]
          - ref: mirror_matrix_middle_top
            shift: [-1.5kx-2.5, 0.5ky+1]
          - ref: mirror_matrix_pinky_home
            shift: [-0.5kx-1, 0.5ky]
          - ref: mirror_matrix_pinky_home
            shift: [-0.5kx-1, -0.5ky-1]
          - ref: mirror_matrix_index_home
            shift: [0, -0.5ky-20]
          - ref: mirror_thumb_outer
            shift: [0.5kx+1, -0.5ky-1]
          - ref: mirror_thumb_outer
            shift: [0.5kx+1, 0.5ky+10]
    _board:
      - name: __key_outline
        fillet: 6
    _keycaps:
      - what: rectangle
        size: [capx, capy]
        where:
          - /matrix_.*/
          - /thumb_.*/
    _mcu:
      - what: rectangle
        where: mcu
        size: [xiao_x, xiao_y]
      - what: rectangle
        where: reference_top_center
        size: [8, 6]
    _switches:
      - what: rectangle
        size: [sw_x, sw_y]
        where:
          - /matrix_.*/
          - /thumb_.*/
    keyboard:
      - _board
      - ^_keycaps
      - ^_mcu
    switchplate:
      - _board
      - operation: subtract
        name: _switches
        fillet: 0.5
      - ^_mcu
pcbs:
  kicad:
    outlines:
      main:
        outline: _board
    footprints:
      diode_left:
        what: UMP1NTR
        where:
          - matrix_middle_top
          - matrix_middle_home
        params: 
          pad1: "index_{{row}}"
          pad2: "{{row_net}}"
          pad3: "middle_{{row}}"
          pad4: "ring_{{row}}"
          pad5: "pinky_{{row}}"
        adjust:
          shift: [0, -4.7]
          rotate: 90
      diode_right:
        what: UMP1NTR
        where:
          - mirror_matrix_middle_top
          - mirror_matrix_middle_home
        params: 
          pad1: "mirror_middle_{{row}}"
          pad2: "{{row_net}}"
          pad3: "mirror_index_{{row}}"
          pad4: "mirror_pinky_{{row}}"
          pad5: "mirror_ring_{{row}}"
        adjust:
          shift: [0, -4.7]
          rotate: 90
      diode_thumb:
        what: UMP1NTR
        where: 
          - thumb_outer
        params: 
          pad1: "mirror_home_{{row}}"
          pad2: "{{row_net}}"
          pad3: "home_{{row}}"
          pad4: "outer_{{row}}"
          pad5: "mirror_outer_{{row}}"
        adjust:
          shift: [0, -4.7]
          rotate: -90
      switches:
        what: choc
        where:
          - /matrix_.*/
          - /thumb_.*/
        params:
          from: "{{colrow}}"
          hotswap: true
          to: "{{column_net}}"
      xiao:
        what: xiao-rp2040
        where: mcu