FROM quay.io/fedora/fedora:latest

RUN dnf install -y \
        awk \
        gcc-g++ \
        git \
        libjpeg-turbo-devel \
        npm \
        python3-devel \
        zlib-ng-compat-devel

ENV PATH=$PATH:/workspace/bin
